version: '3'
services:
  nginx:
    build:
      context: ./nginx/
    network_mode: host
    environment:
      ENABLE: "$BLOCK_CLICKJACKING"
      PORT: 8044
      LIFT_UI: localhost:9044
      TARGET_URL: http://localhost:8044

